/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.spec.model

import io.swagger.v3.oas.annotations.media.Schema
import javax.validation.constraints._;
import javax.validation.Valid;

@Schema(name = "ApiResponse", title = "An uploaded response", description = "Describes the result of uploading an image resource")
case class ApiResponse (
  @Valid 
  @Schema(name = "code", `type` = "Integer")
  code: Option[Integer] = None,
  
  @Schema(name = "`type`", `type` = "String")
  `type`: Option[String] = None,
  
  @Schema(name = "message", `type` = "String")
  message: Option[String] = None
)

