/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.spec.model

import io.swagger.v3.oas.annotations.media.Schema
import javax.validation.constraints._;
import javax.validation.Valid;

@Schema(name = "inline_object", title = "", description = "")
case class InlineObject (
  
  // Updated name of the pet
  @Schema(name = "name", `type` = "String", description = "Updated name of the pet")
  name: Option[String] = None,
  
  // Updated status of the pet
  @Schema(name = "status", `type` = "String", description = "Updated status of the pet")
  status: Option[String] = None
)

