/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.spec.model

import io.swagger.v3.oas.annotations.media.Schema
import java.util.Date
import javax.validation.constraints._;
import javax.validation.Valid;

@Schema(name = "Order", title = "Pet Order", description = "An order for a pets from the pet store")
case class Order (
  
  @Schema(name = "id", `type` = "Long")
  id: Option[Long] = None,
  
  @Schema(name = "petId", `type` = "Long")
  petId: Option[Long] = None,
  @Valid 
  @Schema(name = "quantity", `type` = "Integer")
  quantity: Option[Integer] = None,
  
  @Schema(name = "shipDate", `type` = "Date")
  shipDate: Option[Date] = None,
  
  // Order Status
  @Schema(name = "status", `type` = "String", allowableValues = Array("placed", "approved", "delivered"), description = "Order Status")
  status: Option[String] = None,
  
  @Schema(name = "complete", `type` = "Boolean")
  complete: Option[Boolean] = None
)

