/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.model

import io.swagger.v3.oas.annotations.media.Schema
import java.io.File
import javax.validation.constraints._;
import javax.validation.Valid;

@Schema(name = "inline_object_1", title = "", description = "")
case class InlineObject1 (
  
  // Additional data to pass to server
  @Schema(name = "additionalMetadata", `type` = "String", description = "Additional data to pass to server")
  additionalMetadata: Option[String] = None,
  
  // file to upload
  @Schema(name = "file", `type` = "File", description = "file to upload")
  file: Option[File] = None
)

