/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.model

import org.openapitools.server.api.DefaultJsonFormats
import spray.json._

object ModelFormats extends DefaultJsonFormats {

       implicit val formatApiResponse: RootJsonFormat[ApiResponse] = jsonFormat3(ApiResponse)
       implicit val formatCategory: RootJsonFormat[Category] = jsonFormat2(Category)
       implicit val formatInlineObject: RootJsonFormat[InlineObject] = jsonFormat2(InlineObject)
       implicit val formatInlineObject1: RootJsonFormat[InlineObject1] = jsonFormat2(InlineObject1)
       implicit val formatOrder: RootJsonFormat[Order] = jsonFormat6(Order)
       implicit val formatPet: RootJsonFormat[Pet] = jsonFormat6(Pet)
       implicit val formatTag: RootJsonFormat[Tag] = jsonFormat2(Tag)
       implicit val formatUser: RootJsonFormat[User] = jsonFormat8(User)
}