/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.model

import io.swagger.v3.oas.annotations.media.Schema
import javax.validation.constraints._;
import javax.validation.Valid;

@Schema(name = "Pet", title = "a Pet", description = "A pet for sale in the pet store")
case class Pet (
  
  @Schema(name = "id", `type` = "Long")
  id: Option[Long] = None,
  @Valid 
  @Schema(name = "category", `type` = "Category")
  category: Option[Category] = None,
  @NotNull 
  @Schema(name = "name", `type` = "String", example="doggie")
  name: String,
  @NotNull 
  @Schema(name = "photoUrls", `type` = "List[String]")
  photoUrls: List[String],
  @Valid 
  @Schema(name = "tags", `type` = "List[Tag]")
  tags: Option[List[Tag]] = None,
  
  // pet status in the store
  @Schema(name = "status", `type` = "String", allowableValues = Array("available", "pending", "sold"), description = "pet status in the store")
  status: Option[String] = None
)

