/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.model

import io.swagger.v3.oas.annotations.media.Schema
import javax.validation.constraints._;
import javax.validation.Valid;

@Schema(name = "User", title = "a User", description = "A User who is purchasing from the pet store")
case class User (
  
  @Schema(name = "id", `type` = "Long")
  id: Option[Long] = None,
  
  @Schema(name = "username", `type` = "String")
  username: Option[String] = None,
  
  @Schema(name = "firstName", `type` = "String")
  firstName: Option[String] = None,
  
  @Schema(name = "lastName", `type` = "String")
  lastName: Option[String] = None,
  
  @Schema(name = "email", `type` = "String")
  email: Option[String] = None,
  
  @Schema(name = "password", `type` = "String")
  password: Option[String] = None,
  
  @Schema(name = "phone", `type` = "String")
  phone: Option[String] = None,
  
  // User Status
  @Schema(name = "userStatus", `type` = "Int", description = "User Status")
  userStatus: Option[Int] = None
)

