/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.spec.api

import org.openapitools.spec.model.ApiResponse
import java.io.File
import org.openapitools.spec.model.Pet

import javax.ws.rs._
import java.io.InputStream
import javax.validation.Valid
import javax.validation.constraints._
import io.swagger.v3.oas.annotations._
import io.swagger.v3.oas.annotations.enums._
import io.swagger.v3.oas.annotations.media.{Content, Schema, ArraySchema}
import io.swagger.v3.oas.annotations.parameters.RequestBody
import io.swagger.v3.oas.annotations.responses
import io.swagger.v3.oas.annotations.tags.{Tag, Tags}
import io.swagger.v3.oas.annotations.security.{SecurityRequirement, SecurityRequirements}
import scala.language.higherKinds

@Path("/pet")
trait PetApiSpec[T[_]] {

  @POST
  @Consumes(Array("application/json", "application/xml"))
  @Operation(
    summary = "Add a new pet to the store",
    description = "",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("write:pets","read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "405",
        description = "Invalid input",
      )
    )
  )
  def addPet(
      @RequestBody(description = "Pet object that needs to be added to the store", required=true)@NotNull @Valid  pet: Pet
): T[Unit]

  @DELETE
  @Path("/{petId}")
  @Operation(
    summary = "Deletes a pet",
    description = "",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("write:pets","read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "400",
        description = "Invalid pet value",
      )
    )
  )
  def deletePet(
      @Parameter(name = "petId", in = ParameterIn.PATH , required = true, description = "Pet id to delete")
      @PathParam("petId") petId: Long, 
      @Parameter(name = "api_key", in = ParameterIn.HEADER, description = "")
      @HeaderParam("api_key") apiKey: String
): T[Unit]

  @GET
  @Path("/findByStatus")
  @Produces(Array("application/xml", "application/json"))
  @Operation(
    summary = "Finds Pets by status",
    description = "Multiple status values can be provided with comma separated strings",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = Array(new Content(array = new ArraySchema(schema = new Schema(implementation = classOf[Pet]))))
      ), 
      new responses.ApiResponse(
        responseCode = "400",
        description = "Invalid status value",
      )
    )
  )
  def findPetsByStatus(
      @Parameter(name = "status", in = ParameterIn.QUERY,required=true, description = "Status values that need to be considered for filter")
      @QueryParam("status") status: Iterable[String]
): T[List[Pet]]

  @GET
  @Path("/findByTags")
  @Produces(Array("application/xml", "application/json"))
  @Operation(
    summary = "Finds Pets by tags",
    description = "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = Array(new Content(array = new ArraySchema(schema = new Schema(implementation = classOf[Pet]))))
      ), 
      new responses.ApiResponse(
        responseCode = "400",
        description = "Invalid tag value",
      )
    )
  )
  def findPetsByTags(
      @Parameter(name = "tags", in = ParameterIn.QUERY,required=true, description = "Tags to filter by")
      @QueryParam("tags") tags: Iterable[String], 
      @Parameter(name = "maxCount", in = ParameterIn.QUERY, description = "Maximum number of items to return")
      @QueryParam("maxCount") maxCount: Integer
): T[List[Pet]]

  @GET
  @Path("/{petId}")
  @Produces(Array("application/xml", "application/json"))
  @Operation(
    summary = "Find pet by ID",
    description = "Returns a single pet",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "api_key")
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = Array(new Content(schema = new Schema(implementation = classOf[Pet])))
      ), 
      new responses.ApiResponse(
        responseCode = "400",
        description = "Invalid ID supplied",
      ), 
      new responses.ApiResponse(
        responseCode = "404",
        description = "Pet not found",
      )
    )
  )
  def getPetById(
      @Parameter(name = "petId", in = ParameterIn.PATH , required = true, description = "ID of pet to return")
      @PathParam("petId") petId: Long
): T[Pet]

  @PUT
  @Consumes(Array("application/json", "application/xml"))
  @Operation(
    summary = "Update an existing pet",
    description = "",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("write:pets","read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "400",
        description = "Invalid ID supplied",
      ), 
      new responses.ApiResponse(
        responseCode = "404",
        description = "Pet not found",
      ), 
      new responses.ApiResponse(
        responseCode = "405",
        description = "Validation exception",
      )
    )
  )
  def updatePet(
      @RequestBody(description = "Pet object that needs to be added to the store", required=true)@NotNull @Valid  pet: Pet
): T[Unit]

  @POST
  @Path("/{petId}")
  @Consumes(Array("application/x-www-form-urlencoded"))
  @Operation(
    summary = "Updates a pet in the store with form data",
    description = "",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"),
    )
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("write:pets","read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "405",
        description = "Invalid input",
      )
    )
  )
  def updatePetWithForm(
      @Parameter(name = "petId", in = ParameterIn.PATH , required = true, description = "ID of pet that needs to be updated")
      @PathParam("petId") petId: Long, 
      @Parameter(name = "name", description = "Updated name of the pet")
      @FormParam("name") name: String  , 
      @Parameter(name = "status", description = "Updated status of the pet")
      @FormParam("status") status: String  
): T[Unit]

  @POST
  @Path("/{petId}/uploadImage")
  @Consumes(Array("multipart/form-data"))
  @Produces(Array("application/json"))
  @Operation(
    summary = "uploads an image",
    description = "",
  )
  @Tags(
    value = Array(
        new Tag(name = "pet", description = "Everything about your Pets"))
  )
  @SecurityRequirements(
    value = Array(
      new SecurityRequirement(name = "petstore_auth", scopes = Array("write:pets","read:pets"))
    )
  )
  @responses.ApiResponses(
    value = Array(
      new responses.ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = Array(new Content(schema = new Schema(implementation = classOf[ApiResponse])))
      )
    )
  )
  def uploadFile(
      @Parameter(name = "petId", in = ParameterIn.PATH , required = true, description = "ID of pet to update")
      @PathParam("petId") petId: Long, 
      @Parameter(name = "additionalMetadata", description = "Additional data to pass to server")
      @FormParam("additionalMetadata") additionalMetadata:String, 
      
      @FormParam("file") fileFile: File
): T[ApiResponse]
}
