/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.api

import io.swagger.v3.oas.annotations.OpenAPIDefinition
import io.swagger.v3.oas.annotations.info._
import io.swagger.v3.oas.annotations.tags.Tag
import io.swagger.v3.oas.annotations.servers.Server


@OpenAPIDefinition(
    info = new Info(
    title = "OpenAPI Petstore",
    description = "This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.",
    version = "1.0.0",
    license = new License(name = "Apache-2.0", url = "http://www.apache.org/licenses/LICENSE-2.0.html", extensions = Array()),
    termsOfService = ""
  ),
  tags = Array(
    new Tag(name="pet", description = "Everything about your Pets"),
    new Tag(name="store", description = "Access to Petstore orders"),
    new Tag(name="user", description = "Operations about user"),
  ),
  servers = Array(
    new Server(url = "http://petstore.swagger.io/v2", description = "")
  ),
)
trait OpenApiSpec
