/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.api

import org.openapitools.server.model.ApiResponse
import java.io.File
import org.openapitools.server.model.Pet
import scala.concurrent.{ExecutionContext, Future}

class PetApi(implicit ex: ExecutionContext) extends PetApiSpec[Future] (
) {

    override def addPet(pet: Pet): Future[Unit] = ???
    override def deletePet(petId: Long, apiKey: String): Future[Unit] = ???
    override def findPetsByStatus(status: Iterable[String]): Future[List[Pet]] = ???
    override def findPetsByTags(tags: Iterable[String], maxCount: Int): Future[List[Pet]] = ???
    override def getPetById(petId: Long): Future[Pet] = ???
    override def updatePet(pet: Pet): Future[Unit] = ???
    override def updatePetWithForm(petId: Long, name: String, status: String): Future[Unit] = ???
    override def uploadFile(petId: Long, additionalMetadata: String, file: File): Future[ApiResponse] = ???

}
