/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

package org.openapitools.server.api

import org.openapitools.server.model.User
import scala.concurrent.{ExecutionContext, Future}

class UserApi(implicit ex: ExecutionContext) extends UserApiSpec[Future] (
) {

    override def createUser(user: User): Future[Unit] = ???
    override def createUsersWithArrayInput(user: Iterable[User]): Future[Unit] = ???
    override def createUsersWithListInput(user: Iterable[User]): Future[Unit] = ???
    override def deleteUser(username: String): Future[Unit] = ???
    override def getUserByName(username: String): Future[User] = ???
    override def loginUser(username: String, password: String): Future[String] = ???
    override def logoutUser(): Future[Unit] = ???
    override def updateUser(username: String, user: User): Future[Unit] = ???

}
